version: '2'
services:
  #################### Base  ####################

  base: &base
    build: .
    volumes:
      - .:/home/app/app

  #################### CONTAINERS ####################
  aneki_app:
    <<: *base
    container_name: aneki_app
    command: pipenv run python ./manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
